### ISSUE TITLE
Add option to disable progress bar for `computeBayesianMetaAnalysis()`

### ISSUE THREAD

**Issue by schuemie** [OHDSI/EvidenceSynthesis#9]

**Comment by msuchard** [comment]
this should be a straight-forward task passing along a `disableProgressBar` into to the Java code.   @fanbu1995 ?

**Comment by fanbu1995** [comment]
Right, I think the progress bar was written as part of the default logger display for the `Runner` class? See: https://github.com/OHDSI/EvidenceSynthesis/blob/dbea0d2104274cb24be6eea059d32ac869ce2ca0/java/org/ohdsi/mcmc/Runner.java#L91 
I can change the constructor for `getLogger` that takes in a third boolean argument, and then write another constructor for the `Runner` class that takes in this additional boolean argument to allow disabling the progress bar. 

In this case, do we just want to suppress all text output, including things like "Detected data following adaptive grid distribution" that gets printed out every time it reads in data?

**Comment by fanbu1995** [comment]
I just implemented this for both `computeBayesianMetaAnalysis` and `computeHierarchicalMetaAnalysis` in the `develop` branch.

**Comment by schuemie** [comment]
Thanks!

**Comment by schuemie** [comment]
@msuchard , @fanbu1995 : This feature is included in the develop branch, but this branch also has a ton of other changes. Do you think we're in a good spot to create a release from develop?
